'use strict';
const assert = require('assert/strict');
const fs = require('fs');
const os = require('os');
const path = require('path');
const P = require('../lib/chat-profili');
const root = fs.mkdtempSync(path.join(os.tmpdir(), 'studia-chat-profili-'));
const vault = path.join(root, 'vault'), altro = path.join(root, 'altro');
fs.mkdirSync(vault); fs.mkdirSync(altro);
try {
  const iniziale = P.leggi(vault);
  assert.equal(iniziale.profiles.length, 3);
  assert.equal(iniziale.activeId, 'equilibrato');
  assert.equal(fs.existsSync(path.join(vault, '.studia')), false, 'la sola lettura non scrive preset');
  const clonato = P.clona(vault, 'eli5');
  const copia = clonato.profiles.find((p) => p.id === clonato.activeId);
  assert.equal(copia.nome, "Explain like I'm 5 (copia)");
  assert.equal(copia.caricoCognitivo, 'ridotto');
  const salvato = P.salva(vault, { ...copia, nome: 'Il mio profilo', lingua: 'English', preferenze: 'Un esempio di cucina.' });
  assert.equal(salvato.profiles.find((p) => p.id === copia.id).nome, 'Il mio profilo');
  assert.equal(P.leggi(altro).profiles.length, 3, 'i profili sono isolati per vault');
  assert.equal(P.attiva(vault, 'feynman').activeId, 'feynman');
  const dopo = P.elimina(vault, 'feynman');
  assert.notEqual(dopo.activeId, 'feynman');
  assert(!P.leggi(vault).profiles.some((p) => p.id === 'feynman'), 'un preset eliminato non viene ripristinato');
  assert.throws(() => P.salva(vault, { ...copia, lettura: 'diagnosi' }), /Campo/);
  assert.throws(() => P.salva(vault, { ...copia, preferenze: 'x'.repeat(1201) }), /Campo/);
  assert.throws(() => P.clona(vault, '../escape'), /Identificatore/);
  assert.throws(() => P.attiva(vault, 'non-esiste'), /non trovato/);
  for (const p of P.leggi(vault).profiles.slice(1)) P.elimina(vault, p.id);
  assert.throws(() => P.elimina(vault, P.leggi(vault).activeId), /almeno un profilo/);
  const before = fs.readFileSync(path.join(vault, '.studia', 'chat-profili.json'), 'utf8');
  assert.equal(JSON.parse(before).version, 1);
  assert(!fs.readdirSync(path.join(vault, '.studia')).some((f) => f.includes('.tmp-')));
  fs.writeFileSync(path.join(vault, '.studia', 'chat-profili.json'), '{invalido');
  assert.throws(() => P.salva(vault, copia), SyntaxError, 'non sovrascrive un archivio corrotto');
  assert.equal(fs.readFileSync(path.join(vault, '.studia', 'chat-profili.json'), 'utf8'), '{invalido');
  fs.symlinkSync(path.join(vault, '.studia'), path.join(altro, '.studia'));
  assert.throws(() => P.leggi(altro), /simbolico/);
  assert.throws(() => P.salva(altro, copia), /simbolico/);
  console.log('✓ Profili: preset, salvataggio, clone, cancellazione, validazione e isolamento verificati.');
} finally { fs.rmSync(root, { recursive: true, force: true }); }
